### ISSUE TITLE
你好，请问demo里是否支持3开头的比特币地址转账

### ISSUE THREAD

**Issue by azheng95** [pai01234/tokencore#19]
比如，3MtvkwxXtjK99GTvRKCMrfcPfb1CKd4...地址转账给1EN8KQzVYaZXWx8cZtWjxJUCQgfanNR...

**Comment by GalaxySciTech** [comment]
3开头地址转账 属于隔离见证地址交易，目前不支持，如果想支持可以提交pr

**Comment by azheng95** [comment]
你好，可否留个方式，付费咨询下3开头地址的转账签名问题

**Comment by GalaxySciTech** [comment]
https://t.me/GalaxySciTech

**Comment by azheng95** [comment]
好的
